### ISSUE TITLE
Bad Configuration File [Unraid]

### ISSUE THREAD

**Issue by kylehandy123** [psyko-gh/overcrawlrr#11]
Hi,
I'm currently working on setting up a template in Unraid to ideally release publically so its easy for Unraid users to use your app. I've ran into one snag, which is a bad configuration error.

```
[ 2024-08-25 21:28:11.199 ] info: Configuration file changed. Reloading...
[ 2024-08-25 21:28:11.199 ] info: Loading settings...
[ 2024-08-25 21:28:11.273 ] error: Invalid configuration file. [{"instancePath":"/config","schemaPath":"#/properties/config/required","keyword":"required","params":{"missingProperty":"overseerr"},"message":"must have required property 'overseerr'"}]
Error: Invalid configuration file. [{"instancePath":"/config","schemaPath":"#/properties/config/required","keyword":"required","params":{"missingProperty":"overseerr"},"message":"must have required property 'overseerr'"}]
    at Settings.load (/app/lib/settings.js:45:23)
    at Settings.reload (/app/lib/settings.js:18:18)
    at StatWatcher.emit (node:events:519:28)
    at StatWatcher.onchange (node:internal/fs/watchers:92:8)
```

Attached image is the Unraid template layout.
Let me know if you are able to assist at all please!

(I've omitted my Jellyseerr user credentials for obvious reason. Normally, I do have them entered.)

![Screenshot_1275](https://github.com/user-attachments/assets/8050c991-01be-4b4c-842f-2b5782e54a03)

Edit: Here is my config file details.

```
config:
    # ...
    rulesets:
    - name: Reject Movies
      rules:
          - name: Reject less wanted genres
            whenMatch:
                - genre:
                      - animation
                      - romance
                - age: more than 10 years
            action: reject
          - name: New Action Movies
            whenMatch:
                - age: less than 10 years
                - score: above 7
                - genre: action
                - released: yes
            action: accept
```

**Comment by kylehandy123** [comment]
Ah, that makes sense. I updated to the url of my jellyseerr instance, local ip:port.
I'm now getting an issue where it's saying ECONNECT failed?
I'm not home currently so I can't test further, but I'll leave that here. I know I entered the credentials correctly for the account being used.

**Comment by psyko-gh** [comment]
My bad, I guess I was too tired yesterday. The URL should look like `http://localhost:5055/api/v1`

**Comment by al3x1337** [comment]
Just chiming in that i've also experiencing the same error on my Unraid installation.

```
[ 2024-08-26 20:53:50.240 ] info: Loading settings...
[ 2024-08-26 20:53:50.302 ] error: Invalid configuration file. [{"instancePath":"/config","schemaPath":"#/properties/config/required","keyword":"required","params":{"missingProperty":"discovery"},"message":"must have required property 'discovery'"}]
Error: Invalid configuration file. [{"instancePath":"/config","schemaPath":"#/properties/config/required","keyword":"required","params":{"missingProperty":"discovery"},"message":"must have required property 'discovery'"}]
    at Settings.load (/app/lib/settings.js:45:23)
    at Settings.watch (/app/lib/settings.js:78:14)
    at Object.<anonymous> (/app/index.js:70:31)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
[ 2024-08-26 20:53:50.305 ] info: Server is listening at http://localhost:5056 
[ 2024-08-26 20:55:40.311 ] info: Configuration file changed. Reloading...
[ 2024-08-26 20:55:40.311 ] info: Loading settings...
[ 2024-08-26 20:55:40.348 ] error: Invalid configuration file. [{"instancePath":"/config","schemaPath":"#/properties/config/required","keyword":"required","params":{"missingProperty":"discovery"},"message":"must have required property 'discovery'"}]
```

I have it running via Docker Compose Manager using the following config:

```
services:
  overcrawlrr:
    image: ghcr.io/psyko-gh/overcrawlrr:latest
    container_name: overcrawlrr
    restart: unless-stopped
    ports:
      - 5056:5056
    environment:
      - OVERSEERR_USER=EMAIL
      - OVERSEERR_PASSWORD=PASS
    volumes:
      - /mnt/user/appdata/overcrawlrr:/config
      
```

and here is my Overcrawlrr config:

```
config:
    overseerr:
        # required
        apiUrl: http://192.168.1.x:5055/api/v1 #confirmed this is my overseerr url and that it works
        user: EMAIL # required
        password: PASS # required
        # Optional - dryRun will not send requests to Overseerr
        #            allowing you to test your rules
        dryRun: true

    plex:
        apiUrl: http://192.168.1.x:32400/ #my plex url
        plexToken: TOKEN
```
   
I've run New Permissions also, incase that contributed to any issue.

**Comment by kylehandy123** [comment]
Hey @psyko-gh. after updating the apiURL with my IP:PORT, (http://192.168.1.201:5505/api/v1 - I still receive the error "error: connect ECONNREFUSED 192.168.1.201:5505". I attempted using my subdomain (https://request.mydomain.net/api/v1) and received the following "error: Request failed with status code 403". 
Reminder I am using Jellyseerr. 
Thanks for all the help thus far! I'm not sure why this is still being problematic.

**Comment by kylehandy123** [comment]
@al3x1337 Here is my config. Minus the refusal to connect, I don't receive the error you're receiving anymore, so it might be worth a shot. Please fill in your credentials to connect to your Overseerr or Jellyseerr instance, as I've removed mine.

```
config:
    overseerr: # note that the tag has to be overseerr (not jellyseerr, even though you're using Jellyseer)
        apiUrl: 
        user: 
        password: 
        dryRun: true
    discovery:
        # Required
        cron: '30 3 * * *'
        # Required - the overseer streams to search through
        # Possible values: upcoming, popular, trending
        streams:
            - upcoming
            - popular
            - trending
        # Required - the name of the ruleset used to evaluate movies
        ruleset: New Action Movies
    rulesets:
    - name: Reject Movies
      rules:
          - name: Reject less wanted genres
            whenMatch:
                - genre:
                      - animation
                      - romance
                - age: more than 10 years
            action: reject
          - name: New Action Movies
            whenMatch:
                - age: less than 10 years
                - score: above 7
                - genre: action
                - released: yes
            action: accept
```

**Comment by al3x1337** [comment]
> @al3x1337 Here is my config. Minus the refusal to connect, I don't receive the error you're receiving anymore, so it might be worth a shot. Please fill in your credentials to connect to your Overseerr or Jellyseerr instance, as I've removed mine.
> 
> ```
> config:
>     overseerr: # note that the tag has to be overseerr (not jellyseerr, even though you're using Jellyseer)
>         apiUrl: 
>         user: 
>         password: 
>         dryRun: true
>     discovery:
>         # Required
>         cron: '30 3 * * *'
>         # Required - the overseer streams to search through
>         # Possible values: upcoming, popular, trending
>         streams:
>             - upcoming
>             - popular
>             - trending
>         # Required - the name of the ruleset used to evaluate movies
>         ruleset: New Action Movies
>     rulesets:
>     - name: Reject Movies
>       rules:
>           - name: Reject less wanted genres
>             whenMatch:
>                 - genre:
>                       - animation
>                       - romance
>                 - age: more than 10 years
>             action: reject
>           - name: New Action Movies
>             whenMatch:
>                 - age: less than 10 years
>                 - score: above 7
>                 - genre: action
>                 - released: yes
>             action: accept
> ```

Thanks for posting your config, it worked for both overseerr and plex

**Comment by psyko-gh** [comment]
@kylehandy123 a 403 error indicates that your credentials aree wrong, or not passed correctly.

You're injecting them in your container using environment variables, right ?
If so, make sure you have the following in your configuration file:

```yaml
  overseerr:
    user: '{{ OVERSEERR_USER }}'  # the {{ VAR }} tells the config to load envVar named VAR
    password: '{{ OVERSEERR_PASSWORD }}'
```

Since you obfuscated your configuration, I'm not sure whether it's only empty because you removed the value before posting.

**Comment by kylehandy123** [comment]
@psyko-gh So I double checked my creds and they are 100% correct. Still having issues, if i try to passthrough the variables, or if i enter the login creds directly into the config file. Here is the following:
Log:
```
[ 2024-08-27 05:43:32.769 ] info: Loading settings...
[ 2024-08-27 05:43:32.912 ] error: Environment variable 'OVERSEERR_USER' does not exist
Error: Environment variable 'OVERSEERR_USER' does not exist
    at envVar (/app/env.js:9:15)
    at Settings.resolveEnvironmentVariable (/app/lib/settings.js:70:47)
    at Settings.load (/app/lib/settings.js:49:46)
    at Settings.watch (/app/lib/settings.js:78:14)
    at Object.<anonymous> (/app/index.js:70:31)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
[ 2024-08-27 05:43:32.917 ] info: Server is listening at http://localhost:5056 
```

Config:

```
config:
    overseerr: # note that the tag has to be overseerr (not jellyseerr, even though you're using Jellyseer)
        apiUrl: http://192.168.1.201:5505/api/v1/
        user: '{{ OVERSEERR_USER }}'
        password: '{{ OVERSEERR_PASSWORD }}'
        dryRun: true
    discovery:
        # Required
        cron: '30 3 * * *'
        # Required - the overseer streams to search through
        # Possible values: upcoming, popular, trending
        streams:
            - upcoming
            - popular
            - trending
        # Required - the name of the ruleset used to evaluate movies
        ruleset: New Action Movies
    rulesets:
    - name: Reject Movies
      rules:
          - name: Reject less wanted genres
            whenMatch:
                - genre:
                      - animation
                      - romance
                - age: more than 10 years
            action: reject
          - name: New Action Movies
            whenMatch:
                - age: less than 10 years
                - score: above 7
                - genre: action
                - released: yes
            action: accept
```

And a screenshot of my template created for Unraid. I copied these from the docker_compose file provided. Password removed for the screenshot.

![Screenshot_1276](https://github.com/user-attachments/assets/1c0de061-839f-4de6-ad51-e5c622df3753)

**Comment by psyko-gh** [comment]
> my creds and they are 100% correct

I have no doubt that they are correct :), but somehow they are not passed properly to the app.

The error `Error: Environment variable 'OVERSEERR_USER' does not exist` is kind of weird. It should exist in your container.
It's almost like Unraid is not giving the env vars to the container _(sorry, I never used Unraid, so maybe my statement doesn't even make sense)._

Is it a normal behavior that the yellow text `Container variable` includes the `=` sign at the end for user & password? This looks like it will create an env var named `OVERSEERR_USER=` instead of `OVERSEERR_USER`. 

I will look further tonight.

**Comment by kylehandy123** [comment]
I believe it is normal. Removing the = still doesn't work same error of OVERSEERR_USER does not exist. It's very confusing.

**Comment by psyko-gh** [comment]
I definitely think the `=`should not be there. It's not supposed to be part of the variable name

Can you start a shell inside the container by running (replace `overcrawlrr` with your container name):
```sh
docker exec -it overcrawlrr sh
```

and in the resulting shell, check your env vars by issuing a `printenv` command. They should be listed here.

**Comment by kylehandy123** [comment]
Here is the resulting output. I once again redacted the password prior to this command so it shows up as stars, but I can confirm the password does normally show up when I don't redact it.
```
NODE_VERSION=20.17.0
HOSTNAME=dda3ef0317b4
YARN_VERSION=1.22.22
SHLVL=1
HOME=/home/node
HOST_OS=Unraid
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 OVERSEERR_USER=kylehandy123
HOST_HOSTNAME=MainServer
HOST_CONTAINERNAME=Overcrawlrr
PWD=/app
OVERSEERR_PASSWORD=***
TZ=America/New_York
```
Does this look correct to you whatsoever? I know Unraid templates will add a pinch more to the overall environment fields, which is normally fine 99.9% of the time.

**Comment by psyko-gh** [comment]
Here is the issue, somehow your user variable starts with a whitespace. See how the OVERSEERR_USER is indented one space. 
So the acutal name of the var in your container is `_OVERSEERR_USER` _(underscore for illustration, it's actually a whitespace)_ instead of `OVERSEERR_USER`
Unfortunetaly, being unfamiliar with Unraid, I'm not sure where this comes from.

Try doublechecking what you load in Unraid and search for any extra space.

**Comment by kylehandy123** [comment]
So I was able to correct that, thank you for pointing that out to my sleep deprived brain. Despite correcting that, I still get ECONNREFUSED when using local ip:port, and 403 status code with my subdomain. Very odd.

**Comment by psyko-gh** [comment]
Now that I see it, try to use the email associated with your overseerr user in the `OVERSEERR_USER` variable

**Comment by kylehandy123** [comment]
Sorry, I should have mentioned I tried both a Local Jellyseerr account using email, and an Emby account using a username, neither appear to work correctly.

**Comment by psyko-gh** [comment]
The Jellyseerr local account is definitely the way to go. I'm not sure Overcrawlrr can use your main account since the authentication process might be a bit different.

Definitely try and make sure you did the following:
- Define your apiUrl using your subdomain,
- Define the email of your local Jellyseerr account as the user,
- Use the matching password,
- Make sure the env var definition is good using `printenv` command,

Also, check your Overseerr logs. On a fail login attempt, there should be a log like:
`[warn][API]: Failed sign-in attempt using invalid Overseerr password`

Log command: 
`docker logs --tail 100 -f _your_overseerr_container`

Another thing to check is to try and access the apiUrl in a browser, or through a wget command. It should output something like:
```json
{"api":"Overseerr API","version":"1.0"}
```

**Comment by kylehandy123** [comment]
So I made a new user, local only to Jellyseerr, and used its creds to for Overcrawlrr. Log for Jellyseerr state that the password was incorrect, despite copy and pasting the password from Jellyseerr into the Overcrawlrr ENV. 
I also tried to access the URL in a browser, and the output received was: ```{"message":"not found","errors":[{"path":"/api/v1/","message":"not found"}]}```
This appears to be progress of some sorts..?

**Comment by psyko-gh** [comment]
> This appears to be progress of some sorts..?

Yes, kind of... :smile:

> Log for Jellyseerr state that the password was incorrect

Just to make sure, you confirm that you have the `[warn][API]: Failed sign-in attempt` in the Jellyseerr log ?
This indicates that the URL is fine.
That being said, the login is made on `http://apiurl/auth/local`, so it's not even trying to access the `http://apiurl/api/v1` url. So we've not even reached the point of the `{"path":"/api/v1/","message":"not found"}` error.

I just started with a fresh Jellyseerr container, and it works fine.

In Jellyseerr, do you have any option enabled:
- Enable Proxy Support ? By default, it's disabled.
- Enable CSRF Protection ? By default, it's disabled.

_Note: I'm not even sure it would change anything_

Do you have any specific networking/routing configuration in your server setup ?

**Comment by kylehandy123** [comment]
Hey, sorry for the delay. I'm going to provide a lot of logs in this comment as well as answers to the above questions, please bare with me.

I do have:
```2024-08-29T08:02:00.406Z [warn][API]: Failed sign-in attempt using invalid Overseerr password {"ip":"::ffff:172.17.0.1","email":"=kylehandy1234@gmail.com"}``` (This is a burner email, I'm not worried about it being publicly posted here. :) )

In Jellyseerr I do not have "Enable Proxy Support" Enabled, nor do I have "Enable CSRF Protection" enabled.
My networking is as follows:

Docker networks (Automatically created as we all know), NGINX as my Reverse Proxy, all bog standard nothing special added. SSL certs generated by NGINX Lets-Encrypt.

For fun, here's the latest Overcrawlrr log.
```
[ 2024-08-29 08:01:59.862 ] info: Configuration file changed. Reloading...
[ 2024-08-29 08:01:59.881 ] info: Loading settings...
[ 2024-08-29 08:02:00.046 ] info: Settings loaded successfully from /config/settings.yaml
[ 2024-08-29 08:02:00.055 ] info: Successfully loaded ruleset 'Reject Movies' with 2 rules
[ 2024-08-29 08:02:00.057 ] info: Registered Discover job. Next run: Fri Aug 30 2024 03:30:00 GMT-0400 (Eastern Daylight Time)
[ 2024-08-29 08:02:00.058 ] info: Testing overseerr connection...
[ 2024-08-29 08:02:00.416 ] error: Request failed with status code 403
```

**Comment by psyko-gh** [comment]
> `2024-08-29T08:02:00.406Z [warn][API]: Failed sign-in attempt using invalid Overseerr password {"ip":"::ffff:172.17.0.1","email":"=kylehandy1234@gmail.com"}`

There is an `=` sign at the begining of your email. Unless it's supposed to be here, something is wrong with how you pass env variables to your container.
