### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by dhrandy** [psyko-gh/overcrawlrr#16]
[ 2024-08-27 22:12:42.801 ] info: Loading settings...
[ 2024-08-27 22:12:42.869 ] info: Settings loaded successfully from /config/settings.yaml
[ 2024-08-27 22:12:42.870 ] info: Successfully loaded ruleset 'New great movie' with 2 rules
[ 2024-08-27 22:12:42.873 ] info: Registered Discover job. Next run: Wed Aug 28 2024 03:30:00 GMT+0000 (Coordinated Universal Time)
[ 2024-08-27 22:12:42.874 ] info: Testing overseerr connection...
[ 2024-08-27 22:12:42.879 ] info: Server is listening at http://localhost:5056 
[ 2024-08-27 22:12:42.896 ] error: Request failed with status code 404

**Docker Compose**

services:
    overcrawlrr:
        image: ghcr.io/psyko-gh/overcrawlrr:latest
        container_name: overcrawlrr
        restart: unless-stopped
        ports:
            - 5056:5056
        environment:
            - OVERSEERR_USER=Overcrawler
            - OVERSEERR_PASSWORD=redacted

        volumes:
            - /DATA/AppData/OverCrawlerr/config:/config

**settings.yaml**

config:
  overseerr:
    apiUrl: http://redacted:5056/api/v1
    user: Overcrawler # required
    password: redacted # required
    dryRun: false # Optional - dryRun will not send requests to Overseerr 
  discovery:
    # Required
    cron: '30 3 * * *'
    # Required - the overseer streams to search through
    # Possible values: upcoming, popular, trending
    streams:
      - upcoming
      - popular
      - trending
    # Required - the name of the ruleset used to evaluate movies
    ruleset: New great movie # References the ruleset below
  rulesets: # Indentation was wrong
    - name: New great movie
      rules:
        - name: Reject less wanted genres
          whenMatch:
            - genre:
                - animation
                - horror
          action: reject
        - name: New great movies
          whenMatch:
            - age: less than 1 years
            - score: above 7
          action: accept

**Comment by psyko-gh** [comment]
`status code 404` = most likely, your overseerr apiUrl is not correct.

Also not related, but will be an issue after you solve the 404, `OVERSEERR_USER=Overcrawler` user should be the email associated with the account

**Comment by psyko-gh** [comment]
> Btw, thank you for your work, really useful app that needs to be known !

@neilerua973 Thank you. It's not a big project, but I thought it might be useful to others :)

Did you try to curl `http://overseerr_ip:5056/auth/local` or `http://overseerr_ip:5056/api/v1/auth/local` ? The first one will give you a 404. The second should work. _(I was wrong in https://github.com/psyko-gh/overcrawlrr/issues/11#issuecomment-2316253889)_

If you're curl'ing the `.../api/v1/auth/local`, with a GET method, it should reply a JSON like `{"message":"GET method not allowed","errors":[{"path":"/api/v1/auth/local","message":"GET method not allowed"}]}`

I'll update the code to log the Overseerr url when testing it. It might help.

**Comment by dhrandy** [comment]
This can close now.

**Comment by psyko-gh** [comment]
@dhrandy I'm happy to read that it works 

there is a fix in preparation. The score predicate is not working properly when using `score: above X`. I recommend using `score: above X/10`. I'm not sure how badly it can impact your searches.

Having it run once a month is probably enough indeed.

**Comment by neilerua973** [comment]
@psyko-gh 

> Did you try to curl `http://overseerr_ip:5056/auth/local` or `http://overseerr_ip:5056/api/v1/auth/local` ? The first one will give you a 404. The second should work. _(I was wrong in [#11 (comment)](https://github.com/psyko-gh/overcrawlrr/issues/11#issuecomment-2316253889))_

Good point, I just frogot to add /api/v1, thank you ! 😁
